### ISSUE TITLE
Implement Attested Fields for Object Verification in SDK

### ISSUE THREAD

**Issue by adriacidre** [joinself/self-go-sdk#208]
## Description:

The SDK currently verifies each incoming fact by checking if it has been signed by the issuer specified in its payload. This verification process applies to both self-signed facts and third-party signed facts. However, we encountered an issue with the verification process when dealing with non-string fields (i.e., objects) due to their ephemeral nature.

## Issue Detail:

For non-string fields, when a mobile client needs to resend an object, it cannot simply resend the original signed fact. Instead, it has to upload and share a new object, which will be signed with its own keys. This breaks the current chain of trust as the incoming message will be self-signed by the user, and not by the original signer.

## Proposed Solution:

To address this issue, we propose introducing 'Attested Fields' for objects. This will allow mobile clients to provide an additional attestation for specific fields of an object.

For instance, in the case of a passport photo, the original self-verification attestation will be included. The attested field `attested_image_hash` will contain a payload that *includes the original self-verification signed image_hash*. The SDK can then compare the user-signed object hash with the originally self-verification signed image_hash. If both hashes are equal, it indicates that the user-uploaded object and the self-verification signed object are the same. As a result, developers can trust the attestation.

The structure of the payload with the attested field will be as follows:

```json
{
    "iss": "35555262516",
    "jti": "2B834B03-7522-4189-8124-1F412F2AD30C",
    "sub": "35555262516",
    "iat": "2024-06-11T03:34:23.600Z",
    "source": "passport",
    "verified": true,
    "exp": "2024-06-12T03:34:23.000Z",
    "facts": [
        {
            "key": "photo",
            "value": "",
            "objects": [
                {
                    "id": "467816cf-b74e-4797-8fbe-13e90d3e268a",
                    "image_hash": "pI9cV....",
                    "attested_image_hash": {
                        "payload": "eyJpYXQ....",
                        "protected": "eyJh....",
                        "signature": "Cfipc...."
                    },
                    "link": "https://....",
                    "key": "ez4t****",
                    "expires": "1718163263",
                    "mime": "image/jpeg"
                }
            ]
        }
    ]
}
```

The `attested_image_hash` payload will be:

```json
{
    "iat": "2024-05-10T10:36:38.938674141Z",
    "image_hash": "pI9c...",
    "iss": "self_verification",
    "jti": "03dcb906-5fbd-40c0-8344-8e2035c93035",
    "source": "passport",
    "sub": "35555262516",
    "verified": true
}
```

## Proposed interface

The current interface for developers to access the value of an attestation is limited in its ability to handle complex data types. Specifically, the `AttestedValues` method returns an array of strings, which prevents it from returning objects. To make the interface more flexible and accommodate objects, the can change the `AttestedValues` method to return an interface that is compatible with both strings and objects. This change will involve defining a new AttestedValue interface in Go, with methods that allow string representation and saving to a specified path. The proposed interface is as follows:

```go
type AttestedValue interface {
  String()
  Save(path string)
}
```
With this new interface, developers will be able to handle both string and object attestations in a unified way. This change will enhance the flexibility and usability of our SDK for developers.

## Tasks:

- [ ] Implement 'Attested Fields' mechanism in the SDK.
- [ ] Modify [this proposal](https://github.com/joinself/self-go-sdk/pull/204) to work with objects as it's defined on this issue
- [ ] Update the object verification process to handle 'Attested Fields'.
- [ ] Validate the solution with different scenarios to ensure the chain of trust is maintained.
- [ ] Update relevant documentation and tests.

**Comment by adriacidre** [comment]
After further consideration, I'd like to propose a slight adjustment to my approach. Instead of introducing 'Attested Fields' within objects, let's move the objects to the root of the payload. This will simplify our structure and make it more straightforward for developers to handle attestations from these objects.

In this new approach, the payload structure will look like this:
```json
{
    "facts": [
        {
            "fact": "image_hash",
            "attestations": [
                {
                    "payload": "eyJpYXQ......",
                    "protected": "eyJhbGciOi...",
                    "signature": "bqFBtVoW4..."
                }
            ]
        }
    ],
    "objects": [
    	{
            "name": "image hash from attestation",
            "link": "https://api.joinself.com/v1/objects/365d0bb4-cceb-4169-9e64-4be0fcd0cbc9",
            "key": "Base64URL(ChaCha20Poly1305Itef-Secret-Key + Nonce)",
            "expires": 1613738969,
            "pid": "365d0bb4-cceb-4169-9e64-4be0fcd0cbc9",
    	}
    ],
    "jti": "dc53d25f-ce2a-476a-8259-3aeb9a92866c",
    "cid": "03492ae4-36e4-4db7-b283-658a55081e81",
    "status": "accepted",
    "typ": "identities.facts.query.resp",
    "auth": false,
    "aud": "ed1a7569-4a29-46df-9815-f439ee23859d",
    "iss": "63454275323",
    "sub": "63454275323",
    "iat": "2024-06-13T08:27:15.151Z",
    "exp": "2024-06-16T08:27:15.157Z"
}
```

This new approach will still allow the SDK to compare the user-signed object name _(which will contain the hash of the shared object)_ with the originally self-verification signed image_hash. If both hashes are equal, it indicates that the user-uploaded object and the self-verification signed object are the same, allowing developers to trust the attestation.

Furthermore, the recently proposed AttestedValue interface can still be implemented, but with some modifications to accommodate this new approach.
